# Generated by Django 3.1.5 on 2021-01-09 09:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0002_auto_20210109_1517'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-time'], 'verbose_name': 'trận đấu', 'verbose_name_plural': 'trận đấu'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'mùa giải', 'verbose_name_plural': 'mùa giải'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'đội bóng', 'verbose_name_plural': 'đội bóng'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='date',
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ngày giờ thi đấu'),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='season.team', verbose_name='đội khách'),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team_score',
            field=models.IntegerField(verbose_name='bàn thắng đội khách'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='season.team', verbose_name='đội nhà'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team_score',
            field=models.IntegerField(verbose_name='bàn thắng đội nhà'),
        ),
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='season.season', verbose_name='mùa giải'),
        ),
        migrations.AlterField(
            model_name='season',
            name='length',
            field=models.IntegerField(default=38, verbose_name='số vòng'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='tên'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.CharField(max_length=255, verbose_name='huấn luyện viên'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='tên'),
        ),
    ]
