# Generated by Django 3.1.5 on 2021-01-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0005_auto_20210112_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['created_at'], 'verbose_name': 'mùa giải', 'verbose_name_plural': 'mùa giải'},
        ),
        migrations.RemoveField(
            model_name='season',
            name='updated_at',
        ),
    ]
