# Generated by Django 3.2.3 on 2021-05-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0006_auto_20210112_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(related_name='seasons', to='season.Team'),
        ),
        migrations.AlterField(
            model_name='season',
            name='length',
            field=models.PositiveIntegerField(blank=True, default=38, verbose_name='số vòng'),
        ),
        migrations.AlterField(
            model_name='season',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='slug'),
        ),
    ]
