# Generated by Django 3.1.5 on 2021-06-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0007_auto_20210527_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='teams',
            field=models.ManyToManyField(related_name='seasons', to='season.Team', verbose_name='đội bóng'),
        ),
    ]
