# Generated by Django 3.1.5 on 2021-07-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0009_auto_20210710_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='bàn thắng đội khách'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='bàn thắng đội nhà'),
        ),
    ]
