# Generated by Django 3.2.5 on 2021-07-13 16:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('season', '0010_auto_20210710_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='ngày giờ thi đấu'),
        ),
    ]
